import errno
import json
import multiprocessing
import os
import re
import subprocess
import sys
import time
import traceback
import uuid
import zipfile

os.system('ls')
result_directory = './data'

output_files = list()
result_file = os.path.join(result_directory, 'TopHat2_result.zip')

print(result_file)

result_dirs = os.listdir(result_directory)

print(result_dirs)

#tophat2_result_dir_name = list(filter(re.compile('tophat2_result_*').match, result_dirs))

#tophat2_result_dir_name = list(filter(re.compile('TopHat2_result_*').match, result_dirs))

tophat2_result_dir_name = 'TopHat2_result.zip'

print('Name:',tophat2_result_dir_name)


tophat2_result_dir = os.path.join(result_directory, tophat2_result_dir_name)
print('TH2 Dir: ',tophat2_result_dir)

with zipfile.ZipFile(result_file, 'w',
                     zipfile.ZIP_DEFLATED,
                     allowZip64=True) as zip_file:
    for root, dirs, files in os.walk(tophat2_result_dir):
        for file in files:
            if not (file.endswith('.DS_Store')):
                zip_file.write(os.path.join(root, file), file)
                
output_files.append({'path': result_file,
                     'name': os.path.basename(result_file),
                     'label': os.path.basename(result_file),
                     'description': 'File generated by TopHat2 App'})

print(output_files)
